- assets/js/membraneWebRTC.ts
This, like the rest of the JS, assumes only one audio or video track is being streamed up to the SFU. This should close #11.
> Add ability for JS to switch audio/video track

- mix.exs
This might be helpful when linking a project to a local checkout of the repo for development—dependents won't need to `npm ci` every time they start the server.
> Only run npm install if packages are missing

- .gitignore
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- lib/membrane_rtc_engine/track.ex
Add possibility to transport protocol-specific data inside `RTC.Engine.Track`. For now, used only for WebRTC extensions. It is needed for implementing support for outbound TWCC.
> Add ctx to Track struct

- lib/membrane_rtc_engine/engine.ex
This PR introduces one more tag for an opentelemetry span when adding a new endpoint in RTC Engine. The tag name is `state_component_path` and it captures the value of `Membrane.ComponentPath.get_formatted()` so basically pipeline's name. It will allow for tag search done by `membrane_dashboard`.
> Added component_path otel's tag when adding new endpoint

- lib/membrane_rtc_engine/engine.ex
- lib/membrane_rtc_engine/message.ex
- test/membrane_rtc_engine/rtc_test.exs
> Fix `add_peer` function and `Membrane.RTC.Engine.Message.t()`

- lib/membrane_rtc_engine/endpoint.ex
- lib/membrane_rtc_engine/engine.ex
- lib/membrane_rtc_engine/media_event.ex
related to https://github.com/membraneframework/membrane_webrtc_plugin/pull/70
In track_id_to_metadata should be only active tracks.
> Only active tracks are in track_id_to_metadata

- lib/membrane_rtc_engine/engine.ex
We had a RC while removing peers/endpoints because we were assuming that returning action `remove_child` from Membrane callback will immidiately remove given child from Membrane context.
That's not true and can result in desynchronization between our internal state and Membrane ctx i.e. some child can be present in Membrane context but it might be absent in our internal state. 
Current solution can be changed once Membrane starts informing about successful peer/endpoint removal.
> Fix RC in removing peers/endpoints

- assets/js/const.ts
- assets/js/membraneWebRTC.ts
- guides/simulcast.md
- lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
- lib/membrane_rtc_engine/endpoints/webrtc/forwarder.ex
- lib/membrane_rtc_engine/endpoints/webrtc/simulcast_config.ex
- lib/membrane_rtc_engine/endpoints/webrtc/simulcast_tee.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- lib/membrane_rtc_engine/engine.ex
- lib/membrane_rtc_engine/subscription.ex
- test/membrane_rtc_engine/webrtc/forwarder_test.exs
* enhance API for configuring simulcast both on the client and server sides. Now user can choose, which simulcast encodings should be by default enabled on the client side i.e. sent to the server. Besides this, user can choose which encoding should be by default passed to the client from the server. This can be configured per track.
* fix switching between encodings when one of them becomes active or inactive
* refactor a little internal linking mechanism
* now endpoint can subscribe only for one track i.e. it cannot pass list of tracks it subscribes for
> Enhance API for configuring simulcast. Fix switching between available simulcast encodings

- lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
When subscribing to a track we might fail because track we are trying to subscribe to has been deleted just before doing the subscription and we haven't received this information yet. This PR fixes that RC by ignoring `{:error, :invalid_track_id}` returned from `Engine.subscribe`.
The other solution would be to distinct between `:invalid_track_id` and `:track_already_removed` errors. To achieve this we had to introduce buffer for already removed tracks with some arbitrary capacity.
> Fix RC when subscribing to a track

- lib/membrane_rtc_engine/engine.ex
- This happens when using both a WebRTC and a custom Endpoint in RTC Engine
- Given custom Endpoint subscribes to raw tracks, tees are set up
- Change 1: The upstream tee may require pad naming to conform to {:endpoint, id}
- Change 2: Engine.PushOutputTee requires codec
Reproduction:
1. Update the WebRTC to HLS demo with latest versions of everything published by the Membrane team
2. Note that it doesn’t work
3. Note that changes within this fork are needed for the custom endpoint to work
> Fix raw format links

- lib/membrane_rtc_engine/endpoints/hls_endpoint.ex
- lib/membrane_rtc_engine/engine.ex
- lib/membrane_rtc_engine/media_event.ex
- test/membrane_rtc_engine/media_event_test.exs
Reproduction:
1. Add HLS endpoint which subscribes to raw data.
2. Add another custom endpoint which also subscribes to raw data.
3. Observe that it does not work because of incorrect routing and assignment of tees.
4. Use changes in this fork.
5. Observe that both custom endpoints now work and receive the correct streams.
Changes:
1. Fixed HLS endpoint which did not start correctly.
2. Fixed RTC engine so it would hang raw format filters/tees under the track’s tee using pad `{:endpoint, :shared}`, which correctly works with the Simulcast tee.
3. Added general formatting fixes.
> Fix subscribing to tracks in HLS Endpoint. Fix handling multiple raw subscriptions in Engine.

- lib/membrane_rtc_engine/display_manager/display_manager.ex
- lib/membrane_rtc_engine/display_manager/endpoint_manager.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- lib/membrane_rtc_engine/tees/filter_tee.ex
This PR fixes bugs from updating `membrane_core` to `0.10.0` in `FilterTee`. It also slightly changes how tracks are ordered in `DisplayManager`. The highest priority has a track of the longest speaking peer, the next in priority order is the silent peer, which is silent for the shortest time, and then with the least priority are peers which don't send VADs, because e.g: they don't negotiate them in SDP or don't have an audio track.
To test changes you can use this branch: 
https://github.com/membraneframework/membrane_videoroom/tree/test_display_manager
> Fix display manager

- lib/membrane_rtc_engine/endpoints/webrtc/connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/rtp_connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/track_receiver.ex
- lib/membrane_rtc_engine/endpoints/webrtc/variant_selector.ex
- test/membrane_rtc_engine/media_event_test.exs
- test/membrane_rtc_engine/webrtc/rtp_connection_allocator_test.exs
- test/membrane_rtc_engine/webrtc/rtp_munger_test.exs
- test/membrane_rtc_engine/webrtc/variant_selector_test.exs
- test/membrane_rtc_engine/webrtc/variant_tracker_test.exs
- test/membrane_rtc_engine/webrtc/vp8_munger_test.exs
- test/support/webrtc/test_connection_allocator.ex
This PR allows for bwe overuse when adding a new track. This way, when we e.g. start a screen share we don't have to limit the bandwidth already granted  to some other tracks.
> Allow for bwe overuse in certain conditions

- lib/membrane_rtc_engine/endpoints/webrtc/connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/noop_connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/rtp_connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/track_receiver.ex
- lib/membrane_rtc_engine/endpoints/webrtc/variant_selector.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- test/membrane_rtc_engine/webrtc/rtp_connection_allocator_test.exs
- test/membrane_rtc_engine/webrtc/variant_selector_test.exs
- test/support/webrtc/test_connection_allocator.ex
This PR introduces an ability to temporarily disable automatic variant selection. This is done to allow starting on the target variant.
> Enable negotiable mode 100ms after start of stream to allow instantly reaching target variant

- lib/membrane_rtc_engine/endpoints/webrtc/rtp_connection_allocator.ex
- test/membrane_rtc_engine/webrtc/rtp_connection_allocator_test.exs
There was an error in handling a `DOWN` message from the monitored TrackReceiver, related to managing `prober_status`, that caused improperly reallocating of bandwidth that was freed by the death of the TrackReceiver.
> Fix freed bandwidth not being properly reallocated

- lib/membrane_rtc_engine/endpoints/webrtc/track_sender.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
Sometimes it happens that TS sends EOS on non-existing output pad. Always when leaving a room.
My hypothesis is that when we remove endpoint and corresponding tee it might happen that we will remove bin's output pad before sending EOS. Unfortunately I couldn't reproduce the issue with custom logs that would confirm I am right.
> Fix sending EOS in TrackSender

- lib/membrane_rtc_engine/endpoints/webrtc/rtp_munger.ex
- lib/membrane_rtc_engine/endpoints/webrtc/rtp_munger/cache.ex
- test/membrane_rtc_engine/webrtc/rtp_munger/cache_test.exs
- test/membrane_rtc_engine/webrtc/rtp_munger_test.exs
In the current state, RTP Munger won't always drop buffers with duplicated sequence numbers. In particular, the following scenario would result in the following output:
```
1,2,2,3,2 -> 1,2,2,3
```
Notice that only out-of-order duplicates were dropped. The behavior is inconsistent and might be causing a `replay fail` error in SRTP Encryptor (RTC-22).
> Drop duplicated sequence numbers in RTP Munger [RTC-22]

- lib/membrane_rtc_engine/endpoints/webrtc/connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/noop_connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc/rtp_connection_allocator.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- test/membrane_rtc_engine/webrtc/rtp_connection_allocator_test.exs
- test/support/webrtc/test_connection_allocator.ex
RTPConnectionAllocator was linked to a parent process, but it wasn't manually terminated when WebRTC endpoint died, as links don't act if termination reason is `:normal`. This caused a severe and likely increasing resource leak.
To address this, `GenServer.stop/1` invokation was added in `handle_playing_to_prepared`, a symmetric callback to `handle_prepared_to_playing`, in which RtpConnectionAllocator is spawned.
I think manual QA is the way to go here, writing either a unit or an integration test for that is not trivial.
The best option I think is to use [observer](https://www.erlang.org/doc/apps/observer/observer_ug.html) to validate that RTPConnectionAllocator in fact dies.
I have already checked, but further verification is welcome
> [RTC-27] RTPConnectionAllocator doesn't terminate with parent endpoint

- integration_test/test_videoroom/test/integration/simulcast_test.exs
- lib/membrane_rtc_engine/endpoints/webrtc/variant_tracker.ex
- lib/membrane_rtc_engine/endpoints/webrtc_endpoint.ex
- test/membrane_rtc_engine/webrtc/track_sender_test.exs
- test/membrane_rtc_engine/webrtc/variant_tracker_test.exs
This PR should address screensharing freezes. They were caused by the browser's optimization to send only 1 FPS when streaming static content, which caused the Engine to detect the track as inactive and disable it. In this PR a fix is introduced, that changes the activity requirement:
Previously, a track had to send less than 5 packets in one cycle. Now, to be considered inactive, it cannot send a single packet for 3 cycles.
A typical meeting scenario works best here - in the room where simulcast is enabled, share some static content, eg. Jira, change the card and wait a few seconds. I think the type of screensharing makes a difference here - let's test both sharing the entire screen and a single Chrome tab. Previously, the track would have been disabled after around 5-7 seconds, after …
> [RTC-102] Fix screensharing freezes

- lib/membrane_rtc_engine/engine.ex
- test/membrane_rtc_engine/engine_test.exs
Sending `{:new_tracks, []}` was causing EndpointBin in the webrtc plugin thinking it should send offerData. 
See https://github.com/jellyfish-dev/membrane_webrtc_plugin/blob/master/lib/membrane_webrtc_plugin/endpoint_bin.ex#L689
offerData triggers client SDK to send SDP offer and the whole process of establishing the connection starts.
Because there are no tracks in the SDP, ICE fails (we probably generate wrong SDP) and the whole process is repeated.
The initial idea was not to send offerData when there are no tracks on the server side so I fixed it.
> [RTC-228] Don't send new_tracks notification with empty list

- lib/membrane_rtc_engine/endpoints/webrtc/media_event.ex
> Fix `to_type_string/1` for 3rd party endpoints

- engine/CHANGELOG.md
- engine/lib/membrane_rtc_engine/endpoint.ex
- webrtc/CHANGELOG.md
- webrtc/internal_docs/webrtc_media_events.md
- webrtc/lib/webrtc/media_event.ex
- webrtc/lib/webrtc_endpoint.ex
The main objective of this PR is to send information about tracks SimulcastConfig to WebRTC clients so they can identify which tracks are simulcast and which are not. 
It is related to [this PR](https://github.com/jellyfish-dev/membrane-webrtc-js/pull/34)
> RTC-341 Differentiate simulcast and non-simulcast trakcs

- integration_test/test/recording_endpoint_test.exs
- recording/CHANGELOG.md
- recording/lib/edge_timestamp_saver.ex
- recording/lib/last_buffer_timestamp.ex
- recording/lib/recording_endpoint.ex
- recording/lib/reporter.ex
- recording/test/reporter_test.exs
- recording/test/storage/file_test.exs
- recording/test/storage/s3_test.exs
- recording/test/support/mock_track.ex
In the recording report, we need the start timestamp and end timestamp of the track.
> Extend recording report created by RecordingEndpoint

- recording/CHANGELOG.md
- recording/lib/reporter.ex
- recording/test/reporter_test.exs
The origin field in report is necessary to pair audio and video tracks
> Recording Endpoint: add origin to report

- integration_test/test/recording_endpoint_test.exs
- recording/CHANGELOG.md
- recording/lib/guard.ex
- webrtc/CHANGELOG.md
- webrtc/lib/webrtc/rtp_connection_allocator.ex
Changes:
- Don't list S3 object if no files added in Recording endpoint
- RTP connection allocator is started without link in WebRTC endpoint
> Don't list S3 object if no files added in recording
